name: publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - run: dotnet build
      - name: Publish NuGet Luizanac.QueryExtensions
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ./src/Luizanac.QueryExtensions/Luizanac.QueryExtensions.csproj
          PACKAGE_NAME: Luizanac.QueryExtensions
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}