name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build
      
      - name: Publish NuGet Luizanac.QueryExtensions
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ./src/Luizanac.QueryExtensions.Abstractions/Luizanac.QueryExtensions.Abstractions.csproj
          PACKAGE_NAME: Luizanac.QueryExtensions.Abstractions
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
